In [1]:
import numpy as np

# The Basics

In [2]:
a = np.array(
    [1,2,3]
)
a

array([1, 2, 3])

In [30]:
b = np.array(
    [
    [1, 2., 3., 4.],
    [5., 6., 7., 8.]
    ], dtype='float32'
)
b

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]], dtype=float32)

# Get dimensions

In [31]:
a.ndim

1

In [32]:
b.ndim

2

# Get shape

In [33]:
a.shape

(3,)

In [34]:
b.shape

(2, 4)

# Get type

In [35]:
a.dtype

dtype('int32')

In [36]:
b.dtype

dtype('float32')

# Get size

In [37]:
a.itemsize

4

# Get total size

In [39]:
a.nbytes

12

In [42]:
a.size * a.itemsize 

12

In [43]:
b.itemsize

4

In [44]:
b.nbytes

32

# Accessing /Changing specific elements, rows , columns, etc

In [46]:
a = np.array(
    [
    [1,2,3,4,5,6,7],
    [8,9,10,11,12,13, 14]
    ]
)
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [48]:
a[0]

array([1, 2, 3, 4, 5, 6, 7])

In [49]:
a[1]

array([ 8,  9, 10, 11, 12, 13, 14])

# Get a specific element [r, c]

In [50]:
a[1, 5]

13

In [51]:
a[-1, 1]

9

# Get a specific row

In [52]:
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

# Get a specific column

In [53]:
a[:, 0]

array([1, 8])

# Getting a little more fancy [startIndex:endIndex:stepSize]

In [55]:
a[0, 1:6:2]

array([2, 4, 6])

In [57]:
a[0, 1:-1:2]

array([2, 4, 6])

In [58]:
a[1, 5] = 20
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [60]:
a[:,2] = 5
a

array([[ 1,  2,  5,  4,  5,  6,  7],
       [ 8,  9,  5, 11, 12, 20, 14]])

In [62]:
a[:,2] = [1, 2]
a

array([[ 1,  2,  1,  4,  5,  6,  7],
       [ 8,  9,  2, 11, 12, 20, 14]])

# 3d examples

In [82]:
c = np.array(
    [
    [
    [1, 2],
    [3, 4]
    ],
    [
    [5, 6],
    [7, 8]
    ]
    ],
    dtype='int32'
)
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [83]:
c.size

8

In [84]:
c.nbytes

32

In [85]:
c.itemsize

4

In [86]:
c.ndim

3

In [87]:
c.dtype

dtype('int32')

In [88]:
c.shape

(2, 2, 2)

# Get a specific element (work outside in)

In [89]:
c[0, 1, 0]

3

In [90]:
c [:, 1, :]

array([[3, 4],
       [7, 8]])

In [93]:
x = c[:, 1,0]
x

array([3, 7])

In [94]:
x.ndim

1

In [95]:
x.shape

(2,)

# replace

In [97]:
c[:, 1, :] = [
    [9,9],
    [8,8]
]
c

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

# Initialize different types of arrays

In [100]:
zeros = np.zeros(5)
zeros

array([0., 0., 0., 0., 0.])

In [102]:
zeros.shape

(5,)

In [105]:
np.zeros((2,3, 4, 5))

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

# All 1's matrix

In [111]:
np.ones((4,2, 1), dtype='int32')

array([[[1],
        [1]],

       [[1],
        [1]],

       [[1],
        [1]],

       [[1],
        [1]]])

# Any other number

In [112]:
np.full((2,2), 99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

### Full_like method

In [113]:
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

### Use a.shape if we use np.full

In [116]:
np.full(a.shape, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

### Random decimal numbers

In [118]:
np.random.rand(4, 2)

array([[0.88604824, 0.77835997],
       [0.4525661 , 0.0895401 ],
       [0.12595214, 0.33396305],
       [0.48621262, 0.05752761]])

#### Don't pass in a tuple

In [119]:
np.random.rand((1,2))

TypeError: 'tuple' object cannot be interpreted as an integer

In [120]:
np.random.rand(4, 2, 3)

array([[[0.90413239, 0.15011411, 0.88312667],
        [0.16235387, 0.4262929 , 0.08052796]],

       [[0.35138523, 0.70517525, 0.83113185],
        [0.44071402, 0.48605854, 0.14019315]],

       [[0.88930886, 0.81772813, 0.13607504],
        [0.57664533, 0.04815636, 0.59948141]],

       [[0.99275806, 0.218579  , 0.78326747],
        [0.57864165, 0.96772645, 0.87015445]]])

In [122]:
a

array([[ 1,  2,  1,  4,  5,  6,  7],
       [ 8,  9,  2, 11, 12, 20, 14]])

In [123]:
a.shape

(2, 7)

Create a random array of real numbers using random.random_sample() and pass in the shape

In [121]:
np.random.random_sample(a.shape)

array([[0.67575295, 0.1789677 , 0.88567639, 0.85004854, 0.49933927,
        0.86410836, 0.47483164],
       [0.83441607, 0.38016709, 0.4144352 , 0.65264717, 0.75006608,
        0.07024222, 0.18703411]])

# Random integer values

In [130]:
np.random.randint(7, size=(3,3)) # not shape but size

array([[1, 3, 6],
       [1, 4, 3],
       [3, 3, 3]])

In [128]:
np.random.randint(4, 8, size=(3,3))

array([[7, 6, 6],
       [4, 4, 7],
       [4, 6, 4]])

# Identity matrix

In [134]:
np.identity(10, dtype='int32')

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

# Repeat array using np.repeat(arrayToBerepeated, numberOfTimes, axis=?)

In [147]:
arr = np.array([[1,2,3]])
arr1 = np.array([1,2,3])
r1 = np.repeat(arr, 3, axis=0)
r2 = np.repeat(arr1, 3, axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [148]:
r2

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [150]:
arr

array([[1, 2, 3]])

In [149]:
np.repeat(arr, 3, axis=0)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [151]:
np.repeat(arr, 3, axis=1)

array([[1, 1, 1, 2, 2, 2, 3, 3, 3]])

In [153]:
output = np.ones((5,5))
output

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [154]:
z = np.zeros((3,3))
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [156]:
z[1,1] = 9
z

array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

# Note: slicing array[x:y] , array will be sliced from index x to y-1(exclusive)

In [157]:
output[1:4, 1:4] = z 
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

# Be careful when coping arrays!!!!!

In [160]:
a1 = np.array([1,2,3])
a2 = a1
a1

array([1, 2, 3])

In [159]:
a2

array([1, 2, 3])

In [169]:
a2[0] = 11

In [170]:
a1

array([11,  2,  3])

# a1's content has also been changed!! That's because a1 and a2 points to the same content

# To prevent this, we can use np.array.copy() instead

In [171]:
x1 = np.array([1,2,3])
x2 = a1.copy()

In [172]:
x2[0] = 90

In [173]:
x1

array([1, 2, 3])

In [174]:
x2

array([90,  2,  3])

# Mathematics

In [176]:
x3 = np.array([1,2,3,4])
x3

array([1, 2, 3, 4])

In [177]:
x3 + 2

array([3, 4, 5, 6])

In [178]:
x3 - 2

array([-1,  0,  1,  2])

In [179]:
x3 * 2

array([2, 4, 6, 8])

In [180]:
x3 / 2

array([0.5, 1. , 1.5, 2. ])

In [181]:
x3 = x3 + 12

In [182]:
x3

array([13, 14, 15, 16])

In [184]:
x4 = np.array([1,0,1,0])
x3 + x4

array([14, 14, 16, 16])

In [186]:
x3 ** 2

array([169, 196, 225, 256])

# Take the sin()

In [187]:
np.cos(x3)

array([ 0.90744678,  0.13673722, -0.75968791, -0.95765948])

In [188]:
np.sin(x4)

array([0.84147098, 0.        , 0.84147098, 0.        ])

#### For a lot more https://docs.scipy.org/doc/numpy/reference/routines.math.html

# Linear Algebra

In [190]:
x5 = np.ones((2,3))
x5

array([[1., 1., 1.],
       [1., 1., 1.]])

In [192]:
x6 = np.full((3,2), 2)
x6

array([[2, 2],
       [2, 2],
       [2, 2]])

In [193]:
x5 * x6

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

# Use the np.matmul(array1, array2) instead

In [194]:
np.matmul(x5, x6)

array([[6., 6.],
       [6., 6.]])

# Find the determinants

In [197]:
q1 = np.identity(10)

In [198]:
np.linalg.det(q1)

1.0

More linear algebra at https://docs.scipy.org/doc/numpy/reference/routines.linalg.html

# Statistics

In [199]:
stats = np.array([
    [1,2,3],
    [4,5,6]
])

In [200]:
np.min(stats)

1

In [201]:
np.max(stats)

6

In [202]:
np.sum(stats)

21

# Reorganizing Arrays

In [204]:
before = np.array([
    [1,2,3,4],
    [5,6,7,8]
]
)
before

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [207]:
after = before.reshape((8,1))
after

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [208]:
after1 = before.reshape((2,3))

ValueError: cannot reshape array of size 8 into shape (2,3)

In [211]:
before.reshape((4,2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

# Vertically stacking vectors

In [212]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [213]:
np.vstack([v1, v2, v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

# Size also has to be the same to perform horizontal and vertical stack

# Horizontal stack

In [214]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
np.hstack(
    (h1, h2
     ))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# Careful not to use bracket

In [215]:
np.hstack[(h1, h2, h2)]

TypeError: 'function' object is not subscriptable

# Miscellaneous

### Load data from file

In [218]:
fileData = np.genfromtxt('data.txt', delimiter=',')
fileData

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

#### The data has been automatically casted to a floating type

In [219]:
fileData.dtype

dtype('float64')

# We can use astype(format_specifier)  to override that

In [220]:
fileData.astype('int32')

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

In [221]:
fileData.astype('int64')

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int64)

### But the copy is not inplace since the float type is much larger than the int32

In [222]:
fileData = fileData.astype('int32')
fileData

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

##### Now we've got everything in int

### Boolean masking and advance indexing

In [223]:
fileData > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

### The comparision is performed elementwise like the arithmetic operations

### We can place boolean masking into another array to get the desired array

In [224]:
fileData[fileData > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [225]:
np.any(fileData > 50, axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [226]:
np.all(fileData > 50, axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [228]:
np.all(fileData > 50, axis=1) # rows

array([False, False, False])

In [233]:
(fileData > 50) & (fileData < 100)

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [234]:
(fileData > 50 & fileData < 100)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [236]:
~(fileData > 50) & (~(fileData < 100))

array([[False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False]])

In [238]:
~ fileData > 50

array([[False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False]])

In [239]:
fileData > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [240]:
~(fileData>50)

array([[ True,  True,  True,  True, False, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

## Quiz time!!!

#### Given the array above

<img src="array_1_30.png" alt="Supposed to be an array from 1 to 30">

## Splitting numpy arrays into smaller arrays

In [242]:
X = np.array([i for i in range(1,31)])
X

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [250]:
v1, v2, v3, v4, v5, v6 = np.split(X, 6, axis=0)
Z = [v1, v2, v3, v4, v5, v6]
Z

[array([1, 2, 3, 4, 5]),
 array([ 6,  7,  8,  9, 10]),
 array([11, 12, 13, 14, 15]),
 array([16, 17, 18, 19, 20]),
 array([21, 22, 23, 24, 25]),
 array([26, 27, 28, 29, 30])]

In [253]:
S = np.asanyarray(Z)
S

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [254]:
S[2:4, 0:2]

array([[11, 12],
       [16, 17]])

In [273]:
count = 1
a = 1
for i in range(len(S)):
    for j in range(len(S[i])):
        #print(a)
        a += 1
        print(S[i][j+count], end=" ")
        count += 1
        if i + 1 == count: 
            break
    if count == 4: break
    print(f"---> {count}")

---> 6
---> 11
---> 16
---> 21
---> 26
---> 31


In [274]:
S[[0,1,2,3], [1,2,3,4]]

array([ 2,  8, 14, 20])

In [280]:
S[
    [0,1,2, 3, 4], 
    [0,1,2, 3, 4],
]

array([ 1,  7, 13, 19, 25])

In [284]:
S[
    [0,0,4,4,5,5],
    [3,4,3,4,3,4]
]

array([ 4,  5, 24, 25, 29, 30])

In [285]:
S[[0,4,5], 3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])

In [308]:
V = [8,5,3,1,4,7,9]

In [309]:
def bubble(T):
    n = len(T)
    print(T)
    for i in range(n):
        swapped = False
        for j in range(n-1-i):
            if T[j] > T[j+1]: 
                T[j], T[j+1] = T[j+1], T[j]
                swapped = True
                print(T)
        if swapped == False: break 

In [310]:
bubble(V)

[8, 5, 3, 1, 4, 7, 9]
[5, 8, 3, 1, 4, 7, 9]
[5, 3, 8, 1, 4, 7, 9]
[5, 3, 1, 8, 4, 7, 9]
[5, 3, 1, 4, 8, 7, 9]
[5, 3, 1, 4, 7, 8, 9]
[3, 5, 1, 4, 7, 8, 9]
[3, 1, 5, 4, 7, 8, 9]
[3, 1, 4, 5, 7, 8, 9]
[1, 3, 4, 5, 7, 8, 9]
